//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnomalyTracking.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnomalyTypeDb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnomalyTypeDb()
        {
            this.AnomalyDbs = new HashSet<AnomalyDb>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public int ProcessId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnomalyDb> AnomalyDbs { get; set; }
        public virtual ProcessDb ProcessDb { get; set; }
    }
}
