//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnomalyTracking.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnomalyTrackingDbEntities : Shared.Core.Repository.Context.CoreDbContext, AnomalyTracking.Repository.UnitOfWork.IAnomalyTrackingDbContext
    {
        public AnomalyTrackingDbEntities()
            : base("name=AnomalyTrackingDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LvfUserRoleDb> LvfUserRoleDbs { get; set; }
        public virtual DbSet<AnomalyDb> AnomalyDbs { get; set; }
        public virtual DbSet<AnomalyDeclarationDb> AnomalyDeclarationDbs { get; set; }
        public virtual DbSet<AnomalyTypeDb> AnomalyTypeDbs { get; set; }
        public virtual DbSet<CavityDb> CavityDbs { get; set; }
        public virtual DbSet<ClientAddressDb> ClientAddressDbs { get; set; }
        public virtual DbSet<ClientDb> ClientDbs { get; set; }
        public virtual DbSet<FaceDb> FaceDbs { get; set; }
        public virtual DbSet<MoldDb> MoldDbs { get; set; }
        public virtual DbSet<ProcessDb> ProcessDbs { get; set; }
        public virtual DbSet<ProductDb> ProductDbs { get; set; }
        public virtual DbSet<UserDb> UserDbs { get; set; }
    }
}
