//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnomalyTracking.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnomalyDeclarationDb
    {
        public int Id { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ProcessId { get; set; }
        public int CavityId { get; set; }
        public Nullable<int> AnomalyId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual AnomalyDb AnomalyDb { get; set; }
        public virtual CavityDb CavityDb { get; set; }
        public virtual ProcessDb ProcessDb { get; set; }
        public virtual UserDb UserDb { get; set; }
    }
}
