//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnomalyTracking.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnomalyAnomalyTypeDb
    {
        public int Id { get; set; }
        public int AnomalyTypeId { get; set; }
        public int AnomalyId { get; set; }
    
        public virtual AnomalyDb AnomalyDb { get; set; }
        public virtual AnomalyTypeDb AnomalyTypeDb { get; set; }
    }
}
