//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnomalyTracking.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnomalyDb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnomalyDb()
        {
            this.AnomalyDeclarationDbs = new HashSet<AnomalyDeclarationDb>();
            this.FaceDbs = new HashSet<FaceDb>();
        }
    
        public int Id { get; set; }
        public int AnomalyTypeId { get; set; }
        public int FaceId { get; set; }
    
        public virtual AnomalyTypeDb AnomalyTypeDb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnomalyDeclarationDb> AnomalyDeclarationDbs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaceDb> FaceDbs { get; set; }
    }
}
