//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnomalyTracking.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceDb
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public string Position { get; set; }
        public int AnomalyId { get; set; }
    
        public virtual AnomalyDb AnomalyDb { get; set; }
    }
}
